version: '3.8'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: employee_management
    ports:
      - "3306:3306"
  
  go-app:
    build: .
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
